### ISSUE TITLE
验证终止任务出现和统计数据相关的异常

### ISSUE THREAD

**Issue by Hentioe** [Hentioe/policr-mini#156]
## 出错位置

文件：`lib/policr_mini_bot/worker/validation_terminaltor.ex`
行：65

## 日志1:

`[warn] Job failed because {%Ecto.MultipleResultsError{message: "expected at most one result but got 2 in query:\n\nfrom s0 in PolicrMini.Schema.Statistic,\n where: s0.chat_id == ^-1_001_252_544_704 and s0.verification_status == ^:timeout and\n s0.begin_at == ^~U[2022-05-19 00:00:00Z] and s0.end_at == ^~U[2022-05-19 23:59:59Z]\n"}, [{Ecto.Repo.Queryable, :one, 3, [file: 'lib/ecto/repo/queryable.ex', line: 154]}, {PolicrMini.StatisticBusiness, :"-increment_one/3-fun-0-", 3, [file: 'lib/policr_mini/businesses/statistic_business.ex', line: 62]}, {PolicrMini.StatisticBusiness, :increment_trans, 2, [file: 'lib/policr_mini/businesses/statistic_business.ex', line: 94]}, {PolicrMini.StatisticBusiness, :"-increment_one/3-fun-1-", 2, [file: 'lib/policr_mini/businesses/statistic_business.ex', line: 81]}, {Ecto.Adapters.SQL, :"-checkout_or_transaction/4-fun-0-", 3, [file: 'lib/ecto/adapters/sql.ex', line: 1017]}, {DBConnection, :run_transaction, 4, [file: 'lib/db_connection.ex', line: 1512]}, {PolicrMiniBot.Worker.ValidationTerminator, :terminate, 3, [file: 'lib/policr_mini_bot/worker/validation_terminaltor.ex', line: 64]}, {Honeydew.JobRunner, :do_run, 1, [file: 'lib/honeydew/job_runner.ex', line: 58]}]}, abandoning: %Honeydew.Job{by: :policr_mini@084b283f1a10, completed_at: nil, delay_secs: 45, enqueued_at: 1652939830259, failure_private: nil, from: nil, job_monitor: #PID<0.19023.17>, private: -576460752303017774, queue: :validation_terminator, result: nil, started_at: 1652939874882, task: {:terminate, [%PolicrMini.Schema.Verification{__meta__: #Ecto.Schema.Metadata<:loaded, "verifications">, chat: #Ecto.Association.NotLoaded<association :chat is not loaded>, chat_id: -1001252544704, chosen: nil, entrance: :unity, id: 3245356, indices: nil, inserted_at: ~U[2022-05-19 05:57:09Z], message_id: nil, message_snapshot: #Ecto.Association.NotLoaded<association :message_snapshot is not loaded>, message_snapshot_id: nil, seconds: 45, status: :waiting, target_user_id: 5241727210, target_user_language_code: nil, target_user_name: "\uFEFFGroupHelp", updated_at: ~U[2022-05-19 05:57:09Z]}, %PolicrMini.Chats.Scheme{__meta__: #Ecto.Schema.Metadata<:loaded, "schemes">, chat_id: -1001252544704, id: 2754, image_answers_count: nil, inserted_at: ~U[2021-11-13 08:06:36Z], is_highlighted: nil, mention_text: :mosaic_full_name, seconds: 45, service_message_cleanup: nil, timeout_killing_method: :kick, updated_at: ~U[2022-04-17 07:48:53Z], verification_entrance: nil, verification_mode: :image, verification_occasion: nil, wrong_killing_method: :kick}, 45]}}`

## 日志2:

`[warn] Job failed due to exception. %Honeydew.Job{by: :policr_mini@084b283f1a10, completed_at: nil, delay_secs: 45, enqueued_at: 1652939830259, failure_private: nil, from: nil, job_monitor: #PID<0.19023.17>, private: -576460752303017774, queue: :validation_terminator, result: {:error, %Honeydew.Crash{reason: %Ecto.MultipleResultsError{message: "expected at most one result but got 2 in query:\n\nfrom s0 in PolicrMini.Schema.Statistic,\n where: s0.chat_id == ^-1_001_252_544_704 and s0.verification_status == ^:timeout and\n s0.begin_at == ^~U[2022-05-19 00:00:00Z] and s0.end_at == ^~U[2022-05-19 23:59:59Z]\n"}, stacktrace: [{Ecto.Repo.Queryable, :one, 3, [file: 'lib/ecto/repo/queryable.ex', line: 154]}, {PolicrMini.StatisticBusiness, :"-increment_one/3-fun-0-", 3, [file: 'lib/policr_mini/businesses/statistic_business.ex', line: 62]}, {PolicrMini.StatisticBusiness, :increment_trans, 2, [file: 'lib/policr_mini/businesses/statistic_business.ex', line: 94]}, {PolicrMini.StatisticBusiness, :"-increment_one/3-fun-1-", 2, [file: 'lib/policr_mini/businesses/statistic_business.ex', line: 81]}, {Ecto.Adapters.SQL, :"-checkout_or_transaction/4-fun-0-", 3, [file: 'lib/ecto/adapters/sql.ex', line: 1017]}, {DBConnection, :run_transaction, 4, [file: 'lib/db_connection.ex', line: 1512]}, {PolicrMiniBot.Worker.ValidationTerminator, :terminate, 3, [file: 'lib/policr_mini_bot/worker/validation_terminaltor.ex', line: 64]}, {Honeydew.JobRunner, :do_run, 1, [file: 'lib/honeydew/job_runner.ex', line: 58]}], type: :exception}}, started_at: nil, task: {:terminate, [%PolicrMini.Schema.Verification{__meta__: #Ecto.Schema.Metadata<:loaded, "verifications">, chat: #Ecto.Association.NotLoaded<association :chat is not loaded>, chat_id: -1001252544704, chosen: nil, entrance: :unity, id: 3245356, indices: nil, inserted_at: ~U[2022-05-19 05:57:09Z], message_id: nil, message_snapshot: #Ecto.Association.NotLoaded<association :message_snapshot is not loaded>, message_snapshot_id: nil, seconds: 45, status: :waiting, target_user_id: 5241727210, target_user_language_code: nil, target_user_name: "\uFEFFGroupHelp", updated_at: ~U[2022-05-19 05:57:09Z]}, %PolicrMini.Chats.Scheme{__meta__: #Ecto.Schema.Metadata<:loaded, "schemes">, chat_id: -1001252544704, id: 2754, image_answers_count: nil, inserted_at: ~U[2021-11-13 08:06:36Z], is_highlighted: nil, mention_text: :mosaic_full_name, seconds: 45, service_message_cleanup: nil, timeout_killing_method: :kick, updated_at: ~U[2022-04-17 07:48:53Z], verification_entrance: nil, verification_mode: :image, verification_occasion: nil, wrong_killing_method: :kick}, 45]}} ** (Ecto.MultipleResultsError) expected at most one result but got 2 in query: from s0 in PolicrMini.Schema.Statistic, where: s0.chat_id == ^-1_001_252_544_704 and s0.verification_status == ^:timeout and s0.begin_at == ^~U[2022-05-19 00:00:00Z] and s0.end_at == ^~U[2022-05-19 23:59:59Z] (ecto 3.6.2) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3 (policr_mini 0.1.0) lib/policr_mini/businesses/statistic_business.ex:62: anonymous fn/3 in PolicrMini.StatisticBusiness.increment_one/3 (policr_mini 0.1.0) lib/policr_mini/businesses/statistic_business.ex:94: PolicrMini.StatisticBusiness.increment_trans/2 (policr_mini 0.1.0) lib/policr_mini/businesses/statistic_business.ex:81: anonymous fn/2 in PolicrMini.StatisticBusiness.increment_one/3 (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:1017: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4 (db_connection 2.4.0) lib/db_connection.ex:1512: DBConnection.run_transaction/4 (policr_mini 0.1.0) lib/policr_mini_bot/worker/validation_terminaltor.ex:64: PolicrMiniBot.Worker.ValidationTerminator.terminate/3 (honeydew 1.5.0) lib/honeydew/job_runner.ex:58: Honeydew.JobRunner.do_run/1`

**Comment by Hentioe** [comment]
此错误仍未修复，考虑给数据库加锁或将相关数据交给独立的统计服务处理。

**Comment by Hentioe** [comment]
已强制唯一约束，忽略插入错误
