### ISSUE TITLE
未处理的权限检查错误

### ISSUE THREAD

**Issue by Hentioe** [Hentioe/policr-mini#158]
相关日志1：

`[error] Bot permission check failed, details: [chat_id: -111111111, error: %Telegex.Model.Error{description: "Forbidden: bot is not a member of the group chat", error_code: 403}]`

目前这类错误主要集中在非超级群上。处理方式：

- 直接忽略对这类群的权限检查
- 发送不能在非超级群内工作的通知并取消接管

相关日志2

`[error] ** (FunctionClauseError) no function clause matching in PolicrMiniBot.Runner.WorkingChecker.handle_permission_check_error/2 (policr_mini 0.1.0) lib/policr_mini_bot/runner/working_checker.ex:58: PolicrMiniBot.Runner.WorkingChecker.handle_permission_check_error(%Telegex.Model.RequestError{reason: :timeout}, %PolicrMini.Instances.Chat{__meta__: #Ecto.Schema.Metadata<:loaded, "chats">, big_photo_id: nil, description: nil, id: -1111111111111, inserted_at: ~U[2020-06-26 16:13:54Z], invite_link: nil, is_take_over: true, left: nil, permissions: #Ecto.Association.NotLoaded<association :permissions is not loaded>, small_photo_id: nil, tg_can_add_web_page_previews: true, tg_can_change_info: false, tg_can_invite_users: true, tg_can_pin_messages: false, tg_can_send_media_messages: true, tg_can_send_messages: true, tg_can_send_other_messages: true, tg_can_send_polls: true, title: "群标题", type: :supergroup, updated_at: ~U[2020-07-03 15:27:47Z], username: "chat_username"}) (elixir 1.13.4) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2 (policr_mini 0.1.0) lib/policr_mini_bot/runner/working_checker.ex:16: PolicrMiniBot.Runner.WorkingChecker.run/0 (quantum 3.4.0) lib/quantum/executor.ex:98: anonymous fn/4 in Quantum.Executor.run/5 (telemetry 0.4.3) /drone/src/deps/telemetry/src/telemetry.erl:272: :telemetry.span/3 (quantum 3.4.0) lib/quantum/executor.ex:97: anonymous fn/6 in Quantum.Executor.run/5 (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2 (elixir 1.13.4) lib/task/supervised.ex:34: Task.Supervised.reply/4`

这是因为网络超时而引起的错误，处理方式：

- 超时时自动重试（仅针对被超时的单个群）

**Comment by Hentioe** [comment]
已完成日志 1 中的错误处理。
